### PR TITLE
LPS-111893 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-111893

This is only for master.

cc @david-gutierrez-mesa

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
ci:forward

**Pull request closed without merging**
