### PR TITLE
LPS-147067

### PR DESCRIPTION
**Pull request by catarineaguiar**
https://issues.liferay.com/browse/LPS-147067

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
ci:forward

**Comment by david-gutierrez-mesa** [comment]
@catarineaguiar rebase error, can you please rebase and resend.

**Comment by david-gutierrez-mesa** [comment]
ci:close

**Comment by catarineaguiar** [comment]
Rebased here https://github.com/david-gutierrez-mesa/liferay-portal/pull/279

**Pull request closed without merging**
