### PR TITLE
LPS-126268, LPS-126271, LPS-126272, LPS-126273 | master

### PR DESCRIPTION
**Pull request by nikki-pru**
https://issues.liferay.com/browse/LPS-126268
https://issues.liferay.com/browse/LPS-126271
https://issues.liferay.com/browse/LPS-126272
https://issues.liferay.com/browse/LPS-126273

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:stable

**Comment by nikki-pru** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Rebased. See #109

**Pull request closed without merging**
