### PR TITLE
LPS-145558

### PR DESCRIPTION
**Pull request by catarineaguiar**
https://issues.liferay.com/browse/LPS-145558

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by david-gutierrez-mesa** [comment]
ci:test:liferay-online

**Comment by catarineaguiar** [comment]
I don't know why the `"com.liferay.site.initializer.team.extranet"` didn't work if it is set here: https://issues.liferay.com/browse/LPS-140302

**Comment by david-gutierrez-mesa** [comment]
ci:test:liferay-online

**Comment by david-gutierrez-mesa** [comment]
ci:forward

**Pull request closed without merging**
