### PR TITLE
LPS-126264, LPS-126270, LPS-126427, LPS-126453 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-126264
https://issues.liferay.com/browse/LPS-126270
https://issues.liferay.com/browse/LPS-126427
https://issues.liferay.com/browse/LPS-126453

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
Resend it to resolve the conflicts.

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
Resend it to resolve another conflict😒

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Rebased. See #90

**Pull request closed without merging**
