### PR TITLE
LPS-146960

### PR DESCRIPTION
**Pull request by catarineaguiar**
https://issues.liferay.com/browse/LPS-146960

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:liferay-online

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Rebased. See #268

**Comment by david-gutierrez-mesa** [comment]
ci:reopen

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Rebased. See #269

**Pull request closed without merging**
