### PR TITLE
LPS-126428 | Master

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LPS-126428
Submit to master.
@TonyMa888 @brianwulbern

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
ci:forward

**Comment by david-gutierrez-mesa** [comment]
ci:stop

**Comment by david-gutierrez-mesa** [comment]
ci:forward

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Send directly to https://github.com/brianchandotcom/liferay-portal/pull/98472

**Pull request closed without merging**
