### PR TITLE
POSHI-12, LPS-126602 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/POSHI-12

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Send back see Tim-Cao#616

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
Hi @david-gutierrez-mesa, this one works on my machine. I cannot reproduce your error.

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Send to kenjiheigel#738

**Pull request closed without merging**
