### PR TITLE
LPS-126268, LPS-126271, LPS-126272, LPS-126273 | master

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LPS-126268
https://issues.liferay.com/browse/LPS-126271
https://issues.liferay.com/browse/LPS-126272
https://issues.liferay.com/browse/LPS-126273
cc/ @nikki-pru

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:test:sf
ci:test:relevant

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
@david-gutierrez-mesa, resending this under #111

**Comment by david-gutierrez-mesa** [comment]
See #111
Thank you @nikki-pru!

**Pull request closed without merging**
