### PR TITLE
LPS-126382, LPS-126385 | master

### PR DESCRIPTION
**Pull request by Hanlf**
Hi @david-gutierrez-mesa Since the tests belong to Echo, so I send it to you for review, thanks!
https://issues.liferay.com/browse/LPS-126382
https://issues.liferay.com/browse/LPS-126385

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
ci:close

**Comment by david-gutierrez-mesa** [comment]
See #69

**Pull request closed without merging**
