### PR TITLE
LPS-141144

### PR DESCRIPTION
**Pull request by ThalitaCeli**
https://issues.liferay.com/browse/LPS-141144

### CODE REVIEW

**Comment by ThalitaCeli** [comment]
Hi, David. 
Test cases referring to this ticket:
https://issues.liferay.com/browse/LPS-141144

**Comment by ThalitaCeli** [comment]
Hi @david-gutierrez-mesa, could you see the changes? If you need further changes, please let me know.
Thank you.

**Comment by david-gutierrez-mesa** [comment]
ci:forward

**Comment by david-gutierrez-mesa** [comment]
ci:forward

**Pull request closed without merging**
