### PR TITLE
LPS-130922

### PR DESCRIPTION
**Pull request by ozysouza**

### CODE REVIEW

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/david-gutierrez-mesa/liferay-portal/pull/150

**Comment by Tim-Cao** [comment]
ci:close

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Rebased. See #151

**Pull request closed without merging**
