### PR TITLE
LPS-108667 Integration tests for the new remote fetch method

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
ci:test:sf

**Comment by david-gutierrez-mesa** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:stable

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Pull request closed without merging**
