### PR TITLE
LPS-154668 Welcome Site Initializer Tests

### PR DESCRIPTION
**Pull request by jkappler**
https://issues.liferay.com/browse/LPS-154668

### CODE REVIEW

**Comment by jkappler** [comment]
@AlfredSoto, renamed to Welcome and updated the test. Thanks!

Screenshot 2022-05-27 at 08 29 01

**Comment by jkappler** [comment]
@AlfredSoto, @david-gutierrez-mesa, renamed to Liferay Welcome, and updated the tests 


Screenshot 2022-05-27 at 08 35 16

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Rebased. See #336

**Pull request closed without merging**
