### PR TITLE
LRQA-58329 To add ServicePreActionTest.java for Page Template module

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LRQA-58329

cc/ @vicnate5

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
ci:test:sf

**Comment by david-gutierrez-mesa** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
The failure here means this is working :)

**Comment by david-gutierrez-mesa** [comment]
ci:test:sf

**Comment by david-gutierrez-mesa** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
ci:forward

**Pull request closed without merging**
