### PR TITLE
LPS-126216, LPS-126222 | master

### PR DESCRIPTION
**Pull request by nikki-pru**
https://issues.liferay.com/browse/LPS-126216
https://issues.liferay.com/browse/LPS-126222

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Rebased. See #117

**Pull request closed without merging**
