### PR TITLE
LRQA-55316 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-55316

### CODE REVIEW

**Comment by kyle-miho** [comment]
cc: @vicnate5

**Comment by david-gutierrez-mesa** [comment]
ci:test:sf

**Comment by david-gutierrez-mesa** [comment]
ci:test:sf

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Pull request submitted to brianchandotcom#84621

**Pull request closed without merging**
