### PR TITLE
LPS-109621 Add case to assert add Row without Section in DPT

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LPS-109594
https://issues.liferay.com/browse/LPS-110026
https://issues.liferay.com/browse/LPS-109591
https://issues.liferay.com/browse/LPS-109621

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
ci:test:sf

**Comment by david-gutierrez-mesa** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
Your pull request test has been aborted. We are sorry of the inconvenience but QA is in the process of refining the `ci:test:relevant` test suite. Unfortunately this particular pull request test has exceeded the maximum resource limit and will be aborted. Please contact your team's QA representative(s) for next steps. If your team does not have one then please make a post in [#d-quality-assurance](https://liferay.slack.com/archives/CL84ZPHAT)

**Comment by david-gutierrez-mesa** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
ci:stop

**Comment by david-gutierrez-mesa** [comment]
ci:stop

**Pull request closed without merging**
