### PR TITLE
LPS-144166

### PR DESCRIPTION
**Pull request by catarineaguiar**
https://issues.liferay.com/browse/LPS-145310

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:site-initializer-team-extranet

**Review by david-gutierrez-mesa — CHANGES_REQUESTED** [review]

**Comment by catarineaguiar** [comment]
ci:test:liferay-online

**Comment by catarineaguiar** [comment]
The test **CreateTeamExtranetVirtualInstanceByAPI** is failing but its fix was already sent to BChan!

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Rebased. See #255

**Pull request closed without merging**
