### PR TITLE
[LPS-126410 LPS-126412] | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-126410
https://issues.liferay.com/browse/LPS-126412

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Rebased #92

**Pull request closed without merging**
