### PR TITLE
LPS-126459, LPS-126259 | master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-126459
https://issues.liferay.com/browse/LPS-126259

### CODE REVIEW

**Comment by austinchiang** [comment]
@david-gutierrez-mesa Sending to you because these tests look like they are owned by Echo

**Comment by david-gutierrez-mesa** [comment]
ci:test:sf

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Rebasing

**Pull request closed without merging**
