### PR TITLE
lines testing

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by victorg1991** [comment]
ci:test:bundle

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
ci:test:jacoco-report

**Comment by david-gutierrez-mesa** [comment]
ci:close

**Pull request closed without merging**
