### PR TITLE
LPS-131787

### PR DESCRIPTION
**Pull request by ozysouza**
https://issues.liferay.com/browse/LPS-131787

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Review by david-gutierrez-mesa — APPROVED** [review]

**Comment by david-gutierrez-mesa** [comment]
Rebased. See david-gutierrez-mesa

**Comment by david-gutierrez-mesa** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
See https://github.com/david-gutierrez-mesa/liferay-portal/pull/148

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
Ticket number is wrong in commit message should be automation task number

**Comment by Tim-Cao** [comment]
See https://github.com/david-gutierrez-mesa/liferay-portal/pull/149

**Pull request closed without merging**
